"""初始結構：15 張資料表、CHECK 約束與 2 個 View

由 app/models.py 渲染產生（約束與索引名稱沿用最初 Prisma 建立時的命名），
View 定義沿用原 Prisma migration 的手寫 SQL。

Revision ID: 0001
Revises:
Create Date: 2026-10-03
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Building',
    sa.Column('building_id', sa.CHAR(length=4), nullable=False),
    sa.Column('building_name', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('building_id'),
    sa.UniqueConstraint('building_name', name='Building_building_name_key'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_table('Department',
    sa.Column('dept_id', sa.CHAR(length=4), nullable=False),
    sa.Column('dept_name', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('dept_id'),
    sa.UniqueConstraint('dept_name', name='Department_dept_name_key'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_table('Semester',
    sa.Column('semester_id', sa.CHAR(length=4), nullable=False),
    sa.Column('acad_year', sa.SmallInteger(), nullable=False),
    sa.Column('term', mysql.TINYINT(), nullable=False),
    sa.Column('status', sa.Enum('Planning', 'Enrolling', 'InProgress', 'Finished', name='semesterstatus'), server_default='Planning', nullable=False),
    sa.Column('is_current', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.CheckConstraint('term IN (1, 2, 3)', name='chk_semester_term'),
    sa.PrimaryKeyConstraint('semester_id'),
    sa.UniqueConstraint('acad_year', 'term', name='Semester_acad_year_term_key'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_table('UserAccount',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=30), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=100), nullable=False),
    sa.Column('role', sa.Enum('Admin', 'Teacher', 'Student', name='role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('username', name='UserAccount_username_key'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_table('Course',
    sa.Column('course_no', sa.CHAR(length=5), nullable=False),
    sa.Column('course_name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('course_type', sa.Enum('Required', 'Elective', name='coursetype'), nullable=False),
    sa.Column('credit', mysql.TINYINT(), nullable=False),
    sa.Column('dept_id', sa.CHAR(length=4), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint('credit BETWEEN 0 AND 10', name='chk_course_credit'),
    sa.ForeignKeyConstraint(['dept_id'], ['Department.dept_id'], name='Course_dept_id_fkey', onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('course_no'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_table('Room',
    sa.Column('room_code', sa.VARCHAR(length=10), nullable=False),
    sa.Column('building_id', sa.CHAR(length=4), nullable=False),
    sa.Column('seat_capacity', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['Building.building_id'], name='Room_building_id_fkey', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('room_code'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_table('Student',
    sa.Column('student_id', sa.CHAR(length=10), nullable=False),
    sa.Column('student_name', sa.VARCHAR(length=30), nullable=False),
    sa.Column('dept_id', sa.CHAR(length=4), nullable=False),
    sa.Column('grade', mysql.TINYINT(), nullable=False),
    sa.Column('status', sa.Enum('Enrolled', 'Suspended', 'Dropped', name='studentstatus'), nullable=False),
    sa.Column('class_code', sa.CHAR(length=2), nullable=False),
    sa.Column('degree', mysql.TINYINT(), server_default=sa.text('0'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dept_id'], ['Department.dept_id'], name='Student_dept_id_fkey', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['UserAccount.user_id'], name='Student_user_id_fkey', onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('student_id'),
    sa.UniqueConstraint('user_id', name='Student_user_id_key'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_table('Teacher',
    sa.Column('teacher_id', sa.CHAR(length=6), nullable=False),
    sa.Column('teacher_name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('dept_id', sa.CHAR(length=4), nullable=True),
    sa.Column('can_open_section', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dept_id'], ['Department.dept_id'], name='Teacher_dept_id_fkey', onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['UserAccount.user_id'], name='Teacher_user_id_fkey', onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('teacher_id'),
    sa.UniqueConstraint('user_id', name='Teacher_user_id_key'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_table('CurriculumField',
    sa.Column('course_no', sa.CHAR(length=5), nullable=False),
    sa.Column('field_name', sa.VARCHAR(length=50), nullable=False),
    sa.ForeignKeyConstraint(['course_no'], ['Course.course_no'], name='CurriculumField_course_no_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('course_no', 'field_name'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_table('Section',
    sa.Column('section_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course_no', sa.CHAR(length=5), nullable=False),
    sa.Column('semester_id', sa.CHAR(length=4), nullable=False),
    sa.Column('section_code', sa.CHAR(length=2), server_default='01', nullable=False),
    sa.Column('capacity', sa.SmallInteger(), nullable=False),
    sa.Column('status', sa.Enum('Open', 'Cancelled', name='sectionstatus'), server_default='Open', nullable=False),
    sa.Column('created_by', sa.CHAR(length=6), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('capacity BETWEEN 1 AND 500', name='chk_section_capacity'),
    sa.ForeignKeyConstraint(['course_no'], ['Course.course_no'], name='Section_course_no_fkey', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['Teacher.teacher_id'], name='Section_created_by_fkey', onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['semester_id'], ['Semester.semester_id'], name='Section_semester_id_fkey', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('section_id'),
    sa.UniqueConstraint('course_no', 'semester_id', 'section_code', name='Section_course_no_semester_id_section_code_key'),
    sa.UniqueConstraint('section_id', 'semester_id', name='Section_section_id_semester_id_key'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_index('Section_semester_id_status_idx', 'Section', ['semester_id', 'status'], unique=False)
    op.create_table('TeacherPermissionLog',
    sa.Column('log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('teacher_id', sa.CHAR(length=6), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=False),
    sa.Column('changed_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['UserAccount.user_id'], name='TeacherPermissionLog_changed_by_fkey', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['teacher_id'], ['Teacher.teacher_id'], name='TeacherPermissionLog_teacher_id_fkey', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('log_id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_index('TeacherPermissionLog_teacher_id_changed_at_idx', 'TeacherPermissionLog', ['teacher_id', 'changed_at'], unique=False)
    op.create_table('Enrollment',
    sa.Column('student_id', sa.CHAR(length=10), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('Registered', 'Selected', 'Manual', 'NotSelected', 'Withdrawn', name='enrollmentstatus'), nullable=False),
    sa.Column('score', sa.DECIMAL(precision=4, scale=1), nullable=True),
    sa.Column('feedback_rank', mysql.TINYINT(), nullable=True),
    sa.Column('enrolled_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('feedback_rank IS NULL OR feedback_rank BETWEEN 1 AND 10', name='chk_enrollment_feedback'),
    sa.CheckConstraint('score IS NULL OR score BETWEEN 0 AND 100', name='chk_enrollment_score'),
    sa.ForeignKeyConstraint(['section_id'], ['Section.section_id'], name='Enrollment_section_id_fkey', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['Student.student_id'], name='Enrollment_student_id_fkey', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('student_id', 'section_id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_index('Enrollment_section_id_status_idx', 'Enrollment', ['section_id', 'status'], unique=False)
    op.create_table('SectionSchedule',
    sa.Column('schedule_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('semester_id', sa.CHAR(length=4), nullable=False),
    sa.Column('room_code', sa.VARCHAR(length=10), nullable=False),
    sa.Column('weekday', mysql.TINYINT(), nullable=False),
    sa.Column('period', mysql.TINYINT(), nullable=False),
    sa.CheckConstraint('period BETWEEN 1 AND 14', name='chk_schedule_period'),
    sa.CheckConstraint('weekday BETWEEN 1 AND 7', name='chk_schedule_weekday'),
    sa.ForeignKeyConstraint(['room_code'], ['Room.room_code'], name='SectionSchedule_room_code_fkey', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['section_id', 'semester_id'], ['Section.section_id', 'Section.semester_id'], name='SectionSchedule_section_id_semester_id_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('schedule_id'),
    sa.UniqueConstraint('section_id', 'weekday', 'period', name='SectionSchedule_section_id_weekday_period_key'),
    sa.UniqueConstraint('semester_id', 'room_code', 'weekday', 'period', name='uq_room_timeslot'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_index('SectionSchedule_room_code_idx', 'SectionSchedule', ['room_code'], unique=False)
    op.create_table('SectionTeacher',
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.CHAR(length=6), nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['Section.section_id'], name='SectionTeacher_section_id_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['Teacher.teacher_id'], name='SectionTeacher_teacher_id_fkey', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('section_id', 'teacher_id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_index('SectionTeacher_teacher_id_idx', 'SectionTeacher', ['teacher_id'], unique=False)
    op.create_table('ScoreChangeLog',
    sa.Column('log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.CHAR(length=10), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('old_score', sa.DECIMAL(precision=4, scale=1), nullable=True),
    sa.Column('new_score', sa.DECIMAL(precision=4, scale=1), nullable=True),
    sa.Column('changed_by', sa.Integer(), nullable=False),
    sa.Column('changed_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['UserAccount.user_id'], name='ScoreChangeLog_changed_by_fkey', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id', 'section_id'], ['Enrollment.student_id', 'Enrollment.section_id'], name='ScoreChangeLog_student_id_section_id_fkey', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('log_id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_index('ScoreChangeLog_student_id_section_id_idx', 'ScoreChangeLog', ['student_id', 'section_id'], unique=False)
    # ### end Alembic commands ###

    # ### View：Alembic autogenerate 不處理 View，以 SQL 建立 ###
    # View：開課班級明細（課程 + 學期 + 教師 + 時段 + 已選人數）
    # 使用相關子查詢而非多重 JOIN，避免教師 × 時段 × 選課列數相乘（fan-out）造成計數錯誤
    op.execute(
        """
CREATE VIEW `v_section_detail` AS
SELECT
    s.section_id,
    s.semester_id,
    s.course_no,
    c.course_name,
    c.course_type,
    c.credit,
    s.section_code,
    s.capacity,
    s.status,
    s.created_by,
    (SELECT GROUP_CONCAT(t.teacher_name ORDER BY st.is_primary DESC, t.teacher_id SEPARATOR '、')
       FROM `SectionTeacher` st
       JOIN `Teacher` t ON t.teacher_id = st.teacher_id
      WHERE st.section_id = s.section_id) AS teacher_names,
    (SELECT GROUP_CONCAT(
                CONCAT(ELT(ss.weekday, '一', '二', '三', '四', '五', '六', '日'), ss.period, '@', ss.room_code)
                ORDER BY ss.weekday, ss.period SEPARATOR ',')
       FROM `SectionSchedule` ss
      WHERE ss.section_id = s.section_id) AS schedule_text,
    (SELECT COUNT(*)
       FROM `Enrollment` e
      WHERE e.section_id = s.section_id
        AND e.status IN ('Selected', 'Manual')) AS enrolled_count
FROM `Section` s
JOIN `Course` c ON c.course_no = s.course_no
"""
    )
    # View：學生歷年成績單（只列實際修課的紀錄；大學部 60 分及格、碩博班 70 分及格）
    op.execute(
        """
CREATE VIEW `v_student_transcript` AS
SELECT
    e.student_id,
    s.semester_id,
    s.section_id,
    c.course_no,
    c.course_name,
    c.course_type,
    c.credit,
    e.status,
    e.score,
    CASE
        WHEN e.score IS NULL THEN NULL
        WHEN e.score >= IF(st.degree = 1, 70, 60) THEN 1
        ELSE 0
    END AS passed
FROM `Enrollment` e
JOIN `Section` s  ON s.section_id = e.section_id
JOIN `Course` c   ON c.course_no = s.course_no
JOIN `Student` st ON st.student_id = e.student_id
WHERE e.status IN ('Selected', 'Manual')
"""
    )


def downgrade() -> None:
    op.execute("DROP VIEW IF EXISTS v_student_transcript")
    op.execute("DROP VIEW IF EXISTS v_section_detail")
    op.drop_table('ScoreChangeLog')
    op.drop_table('SectionTeacher')
    op.drop_table('SectionSchedule')
    op.drop_table('Enrollment')
    op.drop_table('TeacherPermissionLog')
    op.drop_table('Section')
    op.drop_table('CurriculumField')
    op.drop_table('Teacher')
    op.drop_table('Student')
    op.drop_table('Room')
    op.drop_table('Course')
    op.drop_table('UserAccount')
    op.drop_table('Semester')
    op.drop_table('Department')
    op.drop_table('Building')
